sudo: required
services:
  - docker

before_install:
  - docker build -t mggyi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mggyi/react-test npm run test
  
after_success:
  - docker build -t mggyi/multi-client ./client
  - docker build -t mggyi/multi-nginx ./nginx
  - docker build -t mggyi/multi-server ./server
  - docker build -t mggyi/multi-worker ./worker
  # Login to the docker ClI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to docker hub
  - docker push mggyi/multi-client
  - docker push mggyi/multi-nginx
  - docker push mggyi/multi-server
  - docker push mggyi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-875157512745'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY