sudo: required
services:
  - docker

before_install:
  - docker build -t nca93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nca93/react-test npm run test
  
after_success:
  - docker build -t nca93/multi-client ./client
  - docker build -t nca93/multi-nginx ./nginx
  - docker build -t nca93/multi-server ./server
  - docker build -t nca93/multi-worker ./worker
  # Login to the docker ClI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to docker hub
  - docker push nca93/multi-client
  - docker push nca93/multi-nginx
  - docker push nca93/multi-server
  - docker push nca93/multi-worker
